// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqfkkQOH1-6VsCga-jez2YJA_fgeDNSIw',
    appId: '1:128586374382:android:ea82970f9eeaa6d41c67ff',
    messagingSenderId: '128586374382',
    projectId: 'trust-finance-6d1ea',
    storageBucket: 'trust-finance-6d1ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwsoRoXtkj_-k8vQ5o4yFvDWAxwrFtB-s',
    appId: '1:128586374382:ios:d2807ffb3ead4d801c67ff',
    messagingSenderId: '128586374382',
    projectId: 'trust-finance-6d1ea',
    storageBucket: 'trust-finance-6d1ea.firebasestorage.app',
    iosBundleId: 'com.example.trustFiniance',
  );
}
